name: flow
version: 1.0.0
base: core24
summary: Deezer client for Ubuntu Touch
description: A Deezer client for Ubuntu Touch
confinement: strict
grade: stable

platforms:
  amd64:
  arm64:
  armhf:

apps:
  flow:
    environment:
      LD_LIBRARY_PATH: ${SNAP}/lib:${SNAP}/usr/lib:${SNAP}
    desktop: flow.desktop
    command: flow
    command-chain:
      - bin/gpu-2404-wrapper
      - bin/lomiri-launch
    plugs:
      - opengl
      - wayland
      - maliit
      - network
      - browser-support
      - network-observe
      - network-control
      - network-bind

plugs:
  lomiri-ui-toolkit:
    interface: content
    target: $SNAP/lomiri-ui-toolkit
    default-provider: lomiri-ui-toolkit-core24
  gpu-2404:
    interface: content
    target: $SNAP/gpu-2404
    default-provider: mesa-2404
  browser-sandbox:
    allow-sandbox: false
    interface: browser-support

layout:
  /usr/share/X11/xkb:
    symlink: $SNAP/lomiri-ui-toolkit/usr/share/X11/xkb
  /usr/share/icons:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/icons
  /usr/share/sounds:
    bind: $SNAP/usr/share/sounds
  /usr/share/qt5:
    bind: $SNAP/lomiri-ui-toolkit/usr/share/qt5

parts:
  app:
    source: .
    plugin: cmake
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/
    build-snaps:
      - lomiri-ui-toolkit-core24
    build-packages:
      - qtbase5-dev
      - qtbase5-dev-tools
      - qtdeclarative5-dev
      - qtquickcontrols2-5-dev
      - qtwebengine5-dev
      - intltool
    stage-packages:
      - libqt5webengine5
    override-prime: |
        craftctl default
        mkdir -p ${CRAFT_PRIME}/bin
        cp -a /snap/lomiri-ui-toolkit-core24/current/command-chain/lomiri-launch ${CRAFT_PRIME}/bin/lomiri-launch
  gpu-2404:
    after:
      - app
    source: https://github.com/canonical/gpu-snap.git
    plugin: dump
    override-prime: |
      craftctl default
      ${CRAFT_PART_SRC}/bin/gpu-2404-cleanup mesa-2404
    prime:
      - bin/gpu-2404-wrapper
